config/routes.rb
WeiboApp::Application.routes.draw do
  get "users/new"
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/signup',   to: 'users#new',   via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<hr class="featurette-divider">
<footer class="footer">
  <div class="container">
    <p class="pull-right"><a href="#">Back to top</a></p>
    <p>制作 by 王旭阳</p>
    <p>
      © 2013 ·
      <a href="/about">About</a>
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-static-top ">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/home">微博</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/home">主页</a></li>
        <li><a href="/about">关于</a></li>
        <li><a href="/help">帮助</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if signed_in? %>
          <li><%= link_to "用户群", users_path %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              账户 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "个人主页", current_user %></li>
              <li><%= link_to "设置", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "登出", signout_path, method: "delete" %>
              </li>
            </ul>
          </li>
      <% else %>
            <li><a href="/signin">登录</a></li>
      <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>微博 | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<%=render "layouts/header" %>

<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
</div>

<%=render "layouts/footer"%>

</body>
</html>